workspace:
  base: /go
  path: src/github.com/jmccann/drone-in-drone

pipeline:
  test:
    image: golang:1.7
    environment:
      - CGO_ENABLED=0
    commands:
      # Disabled: main.go:99: cli.StringSlice composite literal uses unkeyed fields
      # - go vet
      - go test -cover -coverprofile=coverage.out
      - go build -ldflags "-s -w -X main.build=$DRONE_BUILD_NUMBER" -a -tags netgo

  publish:
    image: plugins/docker
    repo: jmccann/drone-in-drone
    tags: [ "latest", "0.5" ]
    when:
      branch: master
      event: push
      local: false
